### ISSUE TITLE
Bug with big category name

### ISSUE THREAD

**Issue by Andrew-Sem** [l3r8yJ/volpi-qa#105]
When i create category with big string, like this: `ashslhdflshdf j hsldhfl hsdfhsldkfhkl sdhlf lsdfh lshdfl hsdlfkh lsdhf ljshd fljhlsdf`, then i got `404` code when trying to `get` questions from it<br/>
<img width="1440" alt="image" src="https://github.com/l3r8yJ/volpi-qa/assets/101043571/f04fe5e2-e344-4357-8d5b-21463daf3753"><br/>
@l3r8yJ take a look at this, please

**Comment by Andrew-Sem** [comment]
Same thing for update & create new questions

**Comment by l3r8yJ** [comment]
won't do it
