### ISSUE TITLE
items order in api

### ISSUE THREAD

**Issue by Andrew-Sem** [l3r8yJ/volpi-qa#106]
Questions 3 & 4 have been added after others. 
<img width="1046" alt="image" src="https://github.com/l3r8yJ/volpi-qa/assets/101043571/55bea187-475d-4d80-84e6-152d95c6938f">

@l3r8yJ do you think that sorting by id, i.e. questions will be added at the end, does it will make more sense? Same thing with categories

**Comment by l3r8yJ** [comment]
@Andrew-Sem we can do in reverse order, wdyt

**Comment by Andrew-Sem** [comment]
@l3r8yJ yep, that will be nice

**Comment by l3r8yJ** [comment]
mine
