### ISSUE TITLE
human-readable error message

### ISSUE THREAD

**Issue by Andrew-Sem** [l3r8yJ/volpi-qa#163]
When user try to enter more than one question with same email, he got this error. It needs to be human-readable
<img width="900" alt="image" src="https://github.com/l3r8yJ/volpi-qa/assets/101043571/b58826a5-b85e-45a6-8483-f1dba6f747d3">

@l3r8yJ, yours

**Comment by Andrew-Sem** [comment]
Now it looks like this
<img width="364" alt="image" src="https://github.com/l3r8yJ/volpi-qa/assets/101043571/28d141e9-4f19-4916-a7fa-790961d1383b">
@l3r8yJ, take a look at this please

**Comment by l3r8yJ** [comment]
@Andrew-Sem should be fixed
