### ISSUE TITLE
Directly deleting unknown questions

### ISSUE THREAD

**Issue by Andrew-Sem** [l3r8yJ/volpi-qa#168]
It will be helpful to add feature to delete unknown question directly, i.e. without giving answer. It should help to filter some spam or duplicated questions

@l3r8yJ, yours

**Comment by l3r8yJ** [comment]
@Andrew-Sem closed as completed

**Comment by Andrew-Sem** [comment]
@l3r8yJ, can u add it to swagger?
<img width="1425" alt="image" src="https://github.com/l3r8yJ/volpi-qa/assets/101043571/33ff5d21-bb73-4328-b6d2-94b6042bac01">

**Comment by l3r8yJ** [comment]
![image](https://github.com/l3r8yJ/volpi-qa/assets/46355873/8aef241f-a5cc-4bac-9020-1a6db21cd966)
As far as I know, it's already there

**Comment by Andrew-Sem** [comment]
@l3r8yJ, sorry, forgot to merge with my own branch
