### ISSUE TITLE
update front for #171

### ISSUE THREAD

**Issue by Andrew-Sem** [l3r8yJ/volpi-qa#176]
update admin client for #171

Mine

**Comment by Andrew-Sem** [comment]
@l3r8yJ maybe better way would be just array of strings instead of this, when getting category names?
<img width="638" alt="image" src="https://github.com/l3r8yJ/volpi-qa/assets/101043571/a5ac6e35-b30d-4c03-a918-cb4bf65f088c">

**Comment by l3r8yJ** [comment]
@Andrew-Sem sure, create an issue please
