### ISSUE TITLE
an empty pop-up window will be displayed

### ISSUE THREAD

**Issue by SergeyShapovaIov** [l3r8yJ/volpi-qa#178]
@Andrew-Sem 
Steps:

- I type something into the search engine
- Erasing symbols in the search

<img width="381" alt="image" src="https://github.com/l3r8yJ/volpi-qa/assets/86362529/b1b728f5-a245-4557-a41d-c10e56fa8b08">

**Comment by Andrew-Sem** [comment]
@SergeyShapovaIov didn't get this bug

https://github.com/l3r8yJ/volpi-qa/assets/101043571/508f0de2-b510-492f-b2f4-72d6fb87e401

Can u please record it?

**Comment by l3r8yJ** [comment]
@SergeyShapovaIov take a look, please

**Comment by Andrew-Sem** [comment]
This issue is appear only when there is no backend. So, chat should handle it
@l3r8yJ, assign me, please
