### ISSUE TITLE
ошибка при повторном заполнении формы редактирования

### ISSUE THREAD

**Issue by SergeyShapovaIov** [l3r8yJ/volpi-qa#34]

**Comment by SergeyShapovaIov** [comment]
https://user-images.githubusercontent.com/86362529/234114340-569b4734-b30a-4435-a410-64b07822765e.mp4

**Comment by SergeyShapovaIov** [comment]
@Andrew-Sem нужно поправить

**Comment by Andrew-Sem** [comment]
Closed in #41 by adding validation
