### ISSUE TITLE
interaction with api for rest client

### ISSUE THREAD

**Issue by Andrew-Sem** [l3r8yJ/volpi-qa#43]

**Comment by l3r8yJ** [comment]
@Andrew-Sem provide details, why do you need crud for rest client?

**Comment by Andrew-Sem** [comment]
@l3r8yJ sry, that's not what I meant
I meant just interaction with api, only read case
Should I rename issue or create new one for my case?

**Comment by l3r8yJ** [comment]
@Andrew-Sem `qa-rest` is only needed for read operations to interact with chat, for crud operations we have `qa-admin`.

**Comment by Andrew-Sem** [comment]
@l3r8yJ yep, that's what I'm talking about

**Comment by l3r8yJ** [comment]
@Andrew-Sem then why do we need crud in `qa-rest`?

**Comment by Andrew-Sem** [comment]
> @l3r8yJ sry, that's not what I meant I meant just interaction with api, only read case Should I rename issue or create new one for my case?

@l3r8yJ We don't need as I corrected myself earlier

**Comment by l3r8yJ** [comment]
@Andrew-Sem we don't have crud operations in qa-rest, I don't undertand what you mean

**Comment by Andrew-Sem** [comment]
@l3r8yJ Everything is very simple. I got a little confused with the name of the issue when I created it. You're right, we only need the read api. By crud I meant interaction with api - reading. 

Finally, I'm just going to change the name of the issue now to make it more sense

**Comment by l3r8yJ** [comment]
@Andrew-Sem so, what’s wrong with interaction with api for rest client?

**Comment by Andrew-Sem** [comment]
@l3r8yJ the problem is its absence. Here is a ticket for me

**Comment by l3r8yJ** [comment]
@Andrew-Sem got you, write something like `i'm in` or etc in future

**Comment by Andrew-Sem** [comment]
@l3r8yJ k
