### ISSUE TITLE
fix cors issue for qa-rest

### ISSUE THREAD

**Issue by Andrew-Sem** [l3r8yJ/volpi-qa#44]
@l3r8yJ yours
<img width="495" alt="image" src="https://user-images.githubusercontent.com/101043571/236532600-65b18db7-5ce3-4dcd-a880-beb9273772e0.png">

**Comment by l3r8yJ** [comment]
@Andrew-Sem why do you need cors requests in `qa-rest`? 

and don't use screenshots, see how to work with markdown

**Comment by Andrew-Sem** [comment]
@l3r8yJ I can't interact with api with this issue 

What do you mean about md?
Just paste screenshots in md style?

**Comment by l3r8yJ** [comment]
@Andrew-Sem about md take a look at [this](https://github.com/eo-cqrs/eo-kafka/pull/251)

**Comment by Andrew-Sem** [comment]
```
![cors issue screenshot](<img src="https://i.ibb.co/hcdWPVZ/236532600-65b18db7-5ce3-4dcd-a880-beb9273772e0.png" alt="236532600-65b18db7-5ce3-4dcd-a880-beb9273772e0" border="0">
```

**Comment by Andrew-Sem** [comment]
@l3r8yJ really don't get it how to use images in ``` symbols as you mentioned earlier. 

Take a look at image above, please. Does it meets the requirements?

**Comment by Andrew-Sem** [comment]
@l3r8yJ
