### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by l3r8yJ** [l3r8yJ/volpi-qa#56]
@Andrew-Sem 

при изменении существующего вопроса можно установить пустые значения, стоит добавить валидацию тоже

**Comment by Andrew-Sem** [comment]
@l3r8yJ изменение лучше проводить над исходными данными, т.е., например, для того чтобы пофиксить опечатку, это крайне полезно
Валидацию добавлю

**Comment by Andrew-Sem** [comment]
@l3r8yJ Для функционала изменения лучше когда по умолчанию в текстовом поле находится изначальное значение
Т.к. редко появляется необходимость изменить что-то полностью, обычно изменения - это фикс опечатки
Также выделить всё и удалить, чтобы написать что-то новое, сильно проще, нежели скопировать и вставить старое, чтобы поменять несколько букв

Hope this make sense ^_^

**Comment by l3r8yJ** [comment]
тикет про то, что при редактировании существующего вопроса/категории можно вписать пустые поля и сохранить, немного не понял к чему это

**Comment by Andrew-Sem** [comment]
@l3r8yJ this issue was closed in pr #61
