### ISSUE TITLE
Not existing user message displayed incorrect 

### ISSUE THREAD

**Issue by l3r8yJ** [l3r8yJ/volpi-qa#76]
rest response
```bash
Writing ["Пользователь с именем: 'adsfdsna' не найден"]
```
But for user is a bad credentials
![image](https://github.com/l3r8yJ/volpi-qa/assets/46355873/2e913dee-2792-43f0-b2ce-9f865fb4dbff)

server will return `404` code i.e - not found, should handle it

@Andrew-Sem yours

**Comment by Andrew-Sem** [comment]
@l3r8yJ, take a look at this, please
It's really strange, but
1) in all cases i've got `500` code, i.e. in postman too:
<img width="682" alt="image" src="https://github.com/l3r8yJ/volpi-qa/assets/101043571/0a764778-aae4-47fd-8536-66338cd30da5"> <br/>
2) in client case, i've got still `500`, but without this message, just like this:
`{code: "ERR_BAD_RESPONSE"
message: "Request failed with status code 500"}`

**Comment by l3r8yJ** [comment]
@Andrew-Sem i've updated master, check again please
