### ISSUE TITLE
Handling for really big text

### ISSUE THREAD

**Issue by Andrew-Sem** [l3r8yJ/volpi-qa#81]
<img width="1386" alt="image" src="https://github.com/l3r8yJ/volpi-qa/assets/101043571/db4d3f4b-db83-44d3-832c-31818f1a4b45">

**Comment by l3r8yJ** [comment]
@Andrew-Sem also, I think we could use a text box to answer instead of just input, what do you think?

**Comment by Andrew-Sem** [comment]
@l3r8yJ yep, I think that we need more space for text, I'll think about it
