### ISSUE TITLE
Static server url 

### ISSUE THREAD

**Issue by l3r8yJ** [l3r8yJ/volpi-qa#87]
It is necessary to make it not static
https://github.com/l3r8yJ/volpi-qa/blob/cf15cf4a33b894f12409b2a2e0621e2d0506872a/qa-admin/src/main/client/src/constants/api.ts#L1

it should look like something like this
https://github.com/l3r8yJ/volpi-qa/blob/cf15cf4a33b894f12409b2a2e0621e2d0506872a/qa-admin/src/main/resources/application.yaml#L14
here we can change it with our env, do something like this, please

for rest too

@Andrew-Sem take a look, please

**Comment by Andrew-Sem** [comment]
@l3r8yJ should api variables be named differently? Or I can use same for both?

**Comment by l3r8yJ** [comment]
@Andrew-Sem just two variables, url for admin and rest
